import type { SymbolId } from '../game/math/SpinResult'
/**
 * REEL AUDIT INPUT — PASTE / REPLACE ONLY THIS ARRAY
 *
 * Paste any five 200-stop reel strips below, then run: npm run reels:audit
 * This file is read-only input for the audit tool and never modifies production math.
 */
// REEL CANDIDATE: QOF-7E98A5F5
export const REEL_STRIPS_TO_AUDIT: readonly (readonly SymbolId[])[] = [
  // Reel 1 — 200 stops
  [
    'SCROLL', 'SCROLL', 'GEM', 'CROWN', 'CHEST', 'CROWN', 'COIN', 'COIN',
    'RING', 'CHEST', 'RING', 'RING', 'COIN', 'RING', 'MAGE', 'SCROLL',
    'CHEST', 'SCROLL', 'COIN', 'SCROLL', 'KNIGHT', 'ARCHER', 'SCROLL', 'SCROLL',
    'DRAGON', 'SCROLL', 'CHEST', 'COIN', 'SCROLL', 'COIN', 'RING', 'COIN',
    'CROWN', 'CROWN', 'COIN', 'RING', 'CHEST', 'COIN', 'SCROLL', 'SCROLL',
    'GEM', 'CROWN', 'RING', 'GEM', 'COIN', 'GEM', 'SCROLL', 'SCROLL',
    'RING', 'RING', 'SCROLL', 'RING', 'RING', 'CROWN', 'ARCHER', 'MAGE',
    'ARCHER', 'SCROLL', 'SCROLL', 'COIN', 'COIN', 'MAGE', 'SCROLL', 'SCROLL',
    'KNIGHT', 'SCROLL', 'SCROLL', 'CHEST', 'RING', 'RING', 'CHEST', 'ARCHER',
    'SCROLL', 'SCROLL', 'CROWN', 'ARCHER', 'RING', 'COIN', 'DRAGON', 'COIN',
    'COIN', 'RING', 'SCROLL', 'CHEST', 'SCROLL', 'RING', 'COIN', 'SCROLL',
    'RING', 'SCROLL', 'COIN', 'RING', 'GEM', 'MAGE', 'CROWN', 'SCROLL',
    'CHEST', 'RING', 'COIN', 'KNIGHT', 'CROWN', 'DRAGON', 'SCROLL', 'DRAGON',
    'COIN', 'MAGE', 'SCROLL', 'SCROLL', 'COIN', 'CHEST', 'COIN', 'KNIGHT',
    'COIN', 'RING', 'CHEST', 'RING', 'SCROLL', 'SCROLL', 'CHEST', 'SCROLL',
    'RING', 'COIN', 'COIN', 'SCROLL', 'SCROLL', 'COIN', 'SCROLL', 'ARCHER',
    'RING', 'ARCHER', 'CHEST', 'CHEST', 'RING', 'SCROLL', 'DRAGON', 'SCROLL',
    'COIN', 'RING', 'RING', 'GEM', 'COIN', 'GEM', 'KNIGHT', 'CHEST',
    'CROWN', 'RING', 'GEM', 'COIN', 'CHEST', 'COIN', 'COIN', 'CROWN',
    'CROWN', 'CHEST', 'SCROLL', 'SCROLL', 'ARCHER', 'COIN', 'CHEST', 'SCROLL',
    'COIN', 'COIN', 'CROWN', 'SCROLL', 'SCROLL', 'CHEST', 'RING', 'GEM',
    'SCROLL', 'KNIGHT', 'RING', 'COIN', 'GEM', 'RING', 'ARCHER', 'RING',
    'KNIGHT', 'COIN', 'GEM', 'SCROLL', 'COIN', 'ARCHER', 'SCROLL', 'COIN',
    'GEM', 'CHEST', 'GEM', 'SCROLL', 'MAGE', 'COIN', 'MAGE', 'ARCHER',
    'RING', 'KNIGHT', 'GEM', 'KNIGHT', 'CHEST', 'CHEST', 'COIN', 'RING',
  ],
  // Reel 2 — 200 stops
  [
    'MAGE', 'SCROLL', 'SCROLL', 'CHEST', 'RING', 'KNIGHT', 'SCROLL', 'CHEST',
    'CROWN', 'ARCHER', 'COIN', 'ARCHER', 'COIN', 'GEM', 'ARCHER', 'SCROLL',
    'COIN', 'SCROLL', 'COIN', 'COIN', 'CHEST', 'SCROLL', 'RING', 'SCROLL',
    'MAGE', 'CHEST', 'MAGE', 'RING', 'ARCHER', 'CHEST', 'RING', 'GEM',
    'CROWN', 'DRAGON', 'CHEST', 'CHEST', 'RING', 'COIN', 'SCROLL', 'RING',
    'SCROLL', 'GEM', 'SCROLL', 'KNIGHT', 'CROWN', 'SCROLL', 'RING', 'COIN',
    'SCROLL', 'RING', 'RING', 'RING', 'ARCHER', 'SCROLL', 'DRAGON', 'RING',
    'SCROLL', 'DRAGON', 'SCROLL', 'CROWN', 'SCROLL', 'CHEST', 'SCROLL', 'COIN',
    'GEM', 'COIN', 'RING', 'COIN', 'COIN', 'CROWN', 'RING', 'RING',
    'COIN', 'COIN', 'CHEST', 'GEM', 'COIN', 'SCROLL', 'RING', 'DRAGON',
    'MAGE', 'COIN', 'SCROLL', 'KNIGHT', 'GEM', 'COIN', 'CHEST', 'MAGE',
    'CROWN', 'COIN', 'SCROLL', 'COIN', 'CROWN', 'SCROLL', 'COIN', 'ARCHER',
    'SCROLL', 'CROWN', 'SCROLL', 'SCROLL', 'CHEST', 'COIN', 'COIN', 'RING',
    'RING', 'SCROLL', 'COIN', 'GEM', 'CHEST', 'CROWN', 'RING', 'SCROLL',
    'COIN', 'SCROLL', 'SCROLL', 'CROWN', 'COIN', 'COIN', 'CHEST', 'SCROLL',
    'CROWN', 'KNIGHT', 'COIN', 'SCROLL', 'COIN', 'RING', 'COIN', 'CHEST',
    'COIN', 'SCROLL', 'CHEST', 'RING', 'KNIGHT', 'ARCHER', 'KNIGHT', 'CHEST',
    'COIN', 'SCROLL', 'RING', 'ARCHER', 'MAGE', 'SCROLL', 'SCROLL', 'RING',
    'GEM', 'SCROLL', 'COIN', 'COIN', 'GEM', 'GEM', 'COIN', 'RING',
    'RING', 'SCROLL', 'CHEST', 'RING', 'SCROLL', 'RING', 'KNIGHT', 'GEM',
    'CROWN', 'RING', 'CHEST', 'SCROLL', 'SCROLL', 'CHEST', 'MAGE', 'SCROLL',
    'SCROLL', 'ARCHER', 'RING', 'CROWN', 'SCROLL', 'COIN', 'RING', 'COIN',
    'GEM', 'CHEST', 'KNIGHT', 'COIN', 'RING', 'RING', 'SCROLL', 'GEM',
    'ARCHER', 'GEM', 'COIN', 'RING', 'CHEST', 'SCROLL', 'SCROLL', 'ARCHER',
    'DRAGON', 'COIN', 'SCROLL', 'COIN', 'CHEST', 'RING', 'KNIGHT', 'SCROLL',
  ],
  // Reel 3 — 200 stops
  [
    'CHEST', 'SCROLL', 'SCROLL', 'RING', 'RING', 'CROWN', 'CHEST', 'CROWN',
    'ARCHER', 'GEM', 'GEM', 'ARCHER', 'CHEST', 'COIN', 'KNIGHT', 'CHEST',
    'SCROLL', 'COIN', 'CHEST', 'COIN', 'CROWN', 'DRAGON', 'SCROLL', 'SCROLL',
    'RING', 'COIN', 'SCROLL', 'MAGE', 'ARCHER', 'RING', 'SCROLL', 'SCROLL',
    'RING', 'CROWN', 'CHEST', 'COIN', 'GEM', 'SCROLL', 'SCROLL', 'COIN',
    'GEM', 'CHEST', 'MAGE', 'GEM', 'MAGE', 'RING', 'CHEST', 'COIN',
    'COIN', 'COIN', 'CHEST', 'COIN', 'KNIGHT', 'SCROLL', 'RING', 'SCROLL',
    'COIN', 'CHEST', 'COIN', 'RING', 'SCROLL', 'CHEST', 'RING', 'COIN',
    'SCROLL', 'RING', 'RING', 'ARCHER', 'KNIGHT', 'GEM', 'RING', 'CROWN',
    'RING', 'CROWN', 'RING', 'DRAGON', 'ARCHER', 'COIN', 'SCROLL', 'RING',
    'SCROLL', 'SCROLL', 'COIN', 'GEM', 'SCROLL', 'COIN', 'SCROLL', 'COIN',
    'SCROLL', 'COIN', 'COIN', 'GEM', 'COIN', 'RING', 'CHEST', 'CHEST',
    'RING', 'RING', 'COIN', 'MAGE', 'RING', 'KNIGHT', 'COIN', 'KNIGHT',
    'CHEST', 'SCROLL', 'CROWN', 'COIN', 'RING', 'CHEST', 'CROWN', 'SCROLL',
    'SCROLL', 'GEM', 'SCROLL', 'COIN', 'COIN', 'CROWN', 'SCROLL', 'COIN',
    'COIN', 'CROWN', 'GEM', 'SCROLL', 'ARCHER', 'CHEST', 'SCROLL', 'DRAGON',
    'CROWN', 'SCROLL', 'RING', 'ARCHER', 'CROWN', 'SCROLL', 'MAGE', 'ARCHER',
    'KNIGHT', 'SCROLL', 'RING', 'COIN', 'SCROLL', 'ARCHER', 'SCROLL', 'COIN',
    'CHEST', 'SCROLL', 'COIN', 'RING', 'SCROLL', 'CHEST', 'SCROLL', 'KNIGHT',
    'RING', 'SCROLL', 'COIN', 'RING', 'SCROLL', 'COIN', 'SCROLL', 'COIN',
    'KNIGHT', 'SCROLL', 'COIN', 'DRAGON', 'COIN', 'RING', 'DRAGON', 'SCROLL',
    'ARCHER', 'GEM', 'ARCHER', 'RING', 'MAGE', 'CHEST', 'SCROLL', 'CHEST',
    'MAGE', 'CHEST', 'COIN', 'RING', 'RING', 'COIN', 'GEM', 'GEM',
    'SCROLL', 'SCROLL', 'RING', 'KNIGHT', 'CROWN', 'GEM', 'CHEST', 'SCROLL',
    'SCROLL', 'SCROLL', 'COIN', 'SCROLL', 'RING', 'RING', 'COIN', 'RING',
  ],
  // Reel 4 — 200 stops
  [
    'RING', 'RING', 'CHEST', 'RING', 'RING', 'MAGE', 'RING', 'SCROLL',
    'COIN', 'SCROLL', 'RING', 'KNIGHT', 'RING', 'SCROLL', 'COIN', 'RING',
    'RING', 'CROWN', 'SCROLL', 'CROWN', 'COIN', 'SCROLL', 'GEM', 'CROWN',
    'CROWN', 'RING', 'SCROLL', 'COIN', 'CHEST', 'COIN', 'RING', 'COIN',
    'KNIGHT', 'SCROLL', 'SCROLL', 'RING', 'SCROLL', 'SCROLL', 'MAGE', 'SCROLL',
    'SCROLL', 'COIN', 'SCROLL', 'CHEST', 'SCROLL', 'SCROLL', 'COIN', 'CHEST',
    'SCROLL', 'ARCHER', 'SCROLL', 'CHEST', 'KNIGHT', 'GEM', 'RING', 'ARCHER',
    'CHEST', 'CHEST', 'COIN', 'COIN', 'MAGE', 'COIN', 'RING', 'COIN',
    'RING', 'COIN', 'SCROLL', 'COIN', 'RING', 'SCROLL', 'ARCHER', 'CHEST',
    'SCROLL', 'ARCHER', 'COIN', 'DRAGON', 'SCROLL', 'SCROLL', 'COIN', 'SCROLL',
    'ARCHER', 'KNIGHT', 'COIN', 'GEM', 'RING', 'GEM', 'RING', 'RING',
    'SCROLL', 'RING', 'DRAGON', 'ARCHER', 'CHEST', 'KNIGHT', 'CHEST', 'SCROLL',
    'KNIGHT', 'SCROLL', 'CROWN', 'RING', 'MAGE', 'SCROLL', 'SCROLL', 'MAGE',
    'SCROLL', 'COIN', 'SCROLL', 'SCROLL', 'COIN', 'COIN', 'SCROLL', 'SCROLL',
    'GEM', 'CROWN', 'SCROLL', 'RING', 'CHEST', 'ARCHER', 'CROWN', 'COIN',
    'COIN', 'SCROLL', 'RING', 'SCROLL', 'COIN', 'GEM', 'COIN', 'CHEST',
    'SCROLL', 'COIN', 'COIN', 'RING', 'COIN', 'ARCHER', 'GEM', 'KNIGHT',
    'SCROLL', 'COIN', 'SCROLL', 'CHEST', 'COIN', 'CROWN', 'CHEST', 'GEM',
    'RING', 'CHEST', 'CHEST', 'COIN', 'COIN', 'RING', 'DRAGON', 'COIN',
    'COIN', 'CHEST', 'RING', 'CROWN', 'CROWN', 'SCROLL', 'KNIGHT', 'GEM',
    'COIN', 'RING', 'ARCHER', 'CHEST', 'CROWN', 'DRAGON', 'GEM', 'GEM',
    'SCROLL', 'MAGE', 'SCROLL', 'COIN', 'COIN', 'CHEST', 'SCROLL', 'CHEST',
    'COIN', 'RING', 'RING', 'MAGE', 'RING', 'KNIGHT', 'CHEST', 'COIN',
    'CHEST', 'GEM', 'RING', 'SCROLL', 'RING', 'GEM', 'DRAGON', 'COIN',
    'CROWN', 'ARCHER', 'SCROLL', 'CROWN', 'GEM', 'SCROLL', 'ARCHER', 'SCROLL',
  ],
  // Reel 5 — 200 stops
  [
    'GEM', 'CHEST', 'RING', 'GEM', 'CROWN', 'RING', 'GEM', 'SCROLL',
    'SCROLL', 'RING', 'SCROLL', 'RING', 'CROWN', 'RING', 'COIN', 'CHEST',
    'COIN', 'COIN', 'RING', 'COIN', 'CHEST', 'ARCHER', 'DRAGON', 'RING',
    'KNIGHT', 'COIN', 'RING', 'GEM', 'SCROLL', 'COIN', 'RING', 'KNIGHT',
    'CHEST', 'RING', 'SCROLL', 'MAGE', 'ARCHER', 'GEM', 'RING', 'CHEST',
    'CHEST', 'CROWN', 'SCROLL', 'COIN', 'RING', 'COIN', 'COIN', 'RING',
    'COIN', 'SCROLL', 'MAGE', 'GEM', 'CHEST', 'COIN', 'COIN', 'CROWN',
    'SCROLL', 'CROWN', 'CHEST', 'RING', 'CROWN', 'ARCHER', 'RING', 'SCROLL',
    'RING', 'COIN', 'SCROLL', 'CHEST', 'CROWN', 'DRAGON', 'COIN', 'SCROLL',
    'COIN', 'SCROLL', 'SCROLL', 'KNIGHT', 'SCROLL', 'ARCHER', 'COIN', 'RING',
    'SCROLL', 'CHEST', 'MAGE', 'COIN', 'RING', 'MAGE', 'ARCHER', 'COIN',
    'RING', 'RING', 'ARCHER', 'CHEST', 'RING', 'KNIGHT', 'RING', 'SCROLL',
    'SCROLL', 'CHEST', 'CHEST', 'KNIGHT', 'SCROLL', 'COIN', 'SCROLL', 'GEM',
    'COIN', 'SCROLL', 'SCROLL', 'COIN', 'CROWN', 'ARCHER', 'CHEST', 'COIN',
    'ARCHER', 'COIN', 'COIN', 'SCROLL', 'CROWN', 'CHEST', 'SCROLL', 'SCROLL',
    'COIN', 'SCROLL', 'CROWN', 'KNIGHT', 'RING', 'SCROLL', 'GEM', 'CHEST',
    'SCROLL', 'RING', 'CHEST', 'RING', 'GEM', 'MAGE', 'ARCHER', 'SCROLL',
    'CROWN', 'COIN', 'RING', 'COIN', 'CHEST', 'CROWN', 'CHEST', 'SCROLL',
    'COIN', 'SCROLL', 'CHEST', 'RING', 'SCROLL', 'SCROLL', 'DRAGON', 'GEM',
    'SCROLL', 'RING', 'GEM', 'SCROLL', 'SCROLL', 'ARCHER', 'RING', 'COIN',
    'COIN', 'KNIGHT', 'DRAGON', 'SCROLL', 'KNIGHT', 'MAGE', 'SCROLL', 'COIN',
    'SCROLL', 'COIN', 'SCROLL', 'COIN', 'RING', 'SCROLL', 'SCROLL', 'CHEST',
    'SCROLL', 'GEM', 'COIN', 'CHEST', 'SCROLL', 'KNIGHT', 'SCROLL', 'COIN',
    'RING', 'RING', 'COIN', 'MAGE', 'COIN', 'SCROLL', 'ARCHER', 'DRAGON',
    'COIN', 'GEM', 'CROWN', 'RING', 'SCROLL', 'COIN', 'SCROLL', 'GEM',
  ],
] as const
