import type { SymbolId } from '../game/math/SpinResult'
/**
 * Frozen generation input that produced production reel set QOF-7E98A5F5.
 *
 * This is intentionally independent from SpinResult.ts so promoting a generated
 * candidate cannot feed the new production ordering back into the optimizer.
 * Change this input only when intentionally beginning a new reel-tuning cycle.
 */
export const REEL_GENERATION_INPUT: readonly (readonly SymbolId[])[] = [
  // Reel 1 — 200 stops
  [
    'DRAGON', 'RING', 'ARCHER', 'GEM', 'RING', 'ARCHER', 'SCROLL', 'RING',
    'COIN', 'CROWN', 'COIN', 'MAGE', 'COIN', 'SCROLL', 'RING', 'CHEST',
    'CHEST', 'COIN', 'ARCHER', 'COIN', 'SCROLL', 'SCROLL', 'KNIGHT', 'COIN',
    'ARCHER', 'RING', 'CROWN', 'SCROLL', 'RING', 'CHEST', 'ARCHER', 'COIN',
    'COIN', 'RING', 'KNIGHT', 'SCROLL', 'CHEST', 'RING', 'SCROLL', 'GEM',
    'RING', 'SCROLL', 'SCROLL', 'MAGE', 'SCROLL', 'CHEST', 'KNIGHT', 'CHEST',
    'CROWN', 'COIN', 'GEM', 'MAGE', 'RING', 'RING', 'SCROLL', 'RING',
    'COIN', 'KNIGHT', 'RING', 'SCROLL', 'DRAGON', 'SCROLL', 'CHEST', 'DRAGON',
    'RING', 'SCROLL', 'CHEST', 'RING', 'COIN', 'COIN', 'ARCHER', 'MAGE',
    'SCROLL', 'CHEST', 'CHEST', 'COIN', 'SCROLL', 'COIN', 'RING', 'ARCHER',
    'CROWN', 'SCROLL', 'CHEST', 'SCROLL', 'COIN', 'SCROLL', 'CHEST', 'SCROLL',
    'RING', 'COIN', 'CROWN', 'CROWN', 'COIN', 'COIN', 'SCROLL', 'GEM',
    'SCROLL', 'COIN', 'SCROLL', 'CROWN', 'RING', 'KNIGHT', 'RING', 'COIN',
    'SCROLL', 'COIN', 'GEM', 'COIN', 'COIN', 'CHEST', 'RING', 'DRAGON',
    'SCROLL', 'COIN', 'ARCHER', 'KNIGHT', 'SCROLL', 'GEM', 'KNIGHT', 'SCROLL',
    'GEM', 'KNIGHT', 'SCROLL', 'GEM', 'SCROLL', 'SCROLL', 'COIN', 'RING',
    'COIN', 'CHEST', 'SCROLL', 'GEM', 'GEM', 'SCROLL', 'RING', 'CHEST',
    'COIN', 'CHEST', 'RING', 'RING', 'COIN', 'RING', 'ARCHER', 'SCROLL',
    'CROWN', 'ARCHER', 'SCROLL', 'CROWN', 'GEM', 'CHEST', 'CHEST', 'GEM',
    'MAGE', 'RING', 'SCROLL', 'MAGE', 'SCROLL', 'SCROLL', 'MAGE', 'SCROLL',
    'RING', 'CROWN', 'CHEST', 'RING', 'GEM', 'ARCHER', 'KNIGHT', 'SCROLL',
    'COIN', 'RING', 'CHEST', 'COIN', 'COIN', 'RING', 'RING', 'DRAGON',
    'CROWN', 'GEM', 'SCROLL', 'CROWN', 'SCROLL', 'COIN', 'CHEST', 'SCROLL',
    'RING', 'COIN', 'COIN', 'SCROLL', 'COIN', 'CHEST', 'SCROLL', 'COIN',
    'CROWN', 'COIN', 'SCROLL', 'COIN', 'COIN', 'SCROLL', 'RING', 'SCROLL',
  ],
  // Reel 2 — 200 stops
  [
    'RING', 'CROWN', 'GEM', 'COIN', 'RING', 'GEM', 'CHEST', 'RING',
    'COIN', 'RING', 'COIN', 'CHEST', 'GEM', 'SCROLL', 'DRAGON', 'RING',
    'COIN', 'CHEST', 'COIN', 'MAGE', 'RING', 'SCROLL', 'MAGE', 'KNIGHT',
    'SCROLL', 'RING', 'SCROLL', 'SCROLL', 'CHEST', 'COIN', 'CHEST', 'RING',
    'COIN', 'ARCHER', 'CHEST', 'COIN', 'CHEST', 'CROWN', 'SCROLL', 'ARCHER',
    'GEM', 'SCROLL', 'COIN', 'CROWN', 'CROWN', 'SCROLL', 'COIN', 'KNIGHT',
    'CROWN', 'SCROLL', 'CROWN', 'SCROLL', 'RING', 'SCROLL', 'GEM', 'CROWN',
    'CROWN', 'COIN', 'RING', 'CHEST', 'COIN', 'COIN', 'MAGE', 'ARCHER',
    'COIN', 'COIN', 'CHEST', 'ARCHER', 'GEM', 'SCROLL', 'DRAGON', 'CHEST',
    'COIN', 'DRAGON', 'CROWN', 'KNIGHT', 'SCROLL', 'SCROLL', 'CHEST', 'SCROLL',
    'COIN', 'COIN', 'COIN', 'SCROLL', 'RING', 'CHEST', 'COIN', 'COIN',
    'GEM', 'RING', 'SCROLL', 'COIN', 'GEM', 'RING', 'SCROLL', 'RING',
    'COIN', 'RING', 'RING', 'MAGE', 'SCROLL', 'CHEST', 'CHEST', 'COIN',
    'RING', 'KNIGHT', 'CROWN', 'SCROLL', 'SCROLL', 'CHEST', 'RING', 'COIN',
    'COIN', 'CROWN', 'COIN', 'SCROLL', 'DRAGON', 'GEM', 'COIN', 'ARCHER',
    'SCROLL', 'SCROLL', 'ARCHER', 'COIN', 'MAGE', 'ARCHER', 'COIN', 'MAGE',
    'SCROLL', 'SCROLL', 'RING', 'SCROLL', 'RING', 'RING', 'ARCHER', 'COIN',
    'SCROLL', 'COIN', 'SCROLL', 'RING', 'CHEST', 'KNIGHT', 'COIN', 'RING',
    'KNIGHT', 'SCROLL', 'RING', 'KNIGHT', 'RING', 'RING', 'SCROLL', 'GEM',
    'CROWN', 'SCROLL', 'COIN', 'ARCHER', 'RING', 'RING', 'CHEST', 'GEM',
    'RING', 'SCROLL', 'SCROLL', 'RING', 'GEM', 'COIN', 'SCROLL', 'CROWN',
    'COIN', 'RING', 'KNIGHT', 'CHEST', 'SCROLL', 'CHEST', 'SCROLL', 'SCROLL',
    'COIN', 'SCROLL', 'COIN', 'SCROLL', 'SCROLL', 'CHEST', 'SCROLL', 'CHEST',
    'MAGE', 'ARCHER', 'RING', 'RING', 'GEM', 'KNIGHT', 'GEM', 'SCROLL',
    'CHEST', 'SCROLL', 'COIN', 'DRAGON', 'SCROLL', 'ARCHER', 'SCROLL', 'SCROLL',
  ],
  // Reel 3 — 200 stops
  [
    'SCROLL', 'SCROLL', 'ARCHER', 'KNIGHT', 'COIN', 'ARCHER', 'SCROLL', 'GEM',
    'RING', 'SCROLL', 'CHEST', 'RING', 'MAGE', 'GEM', 'DRAGON', 'SCROLL',
    'SCROLL', 'COIN', 'COIN', 'CHEST', 'RING', 'COIN', 'SCROLL', 'COIN',
    'COIN', 'RING', 'CHEST', 'SCROLL', 'GEM', 'COIN', 'SCROLL', 'COIN',
    'RING', 'SCROLL', 'CHEST', 'RING', 'CHEST', 'RING', 'SCROLL', 'GEM',
    'COIN', 'RING', 'SCROLL', 'RING', 'GEM', 'SCROLL', 'ARCHER', 'KNIGHT',
    'SCROLL', 'RING', 'COIN', 'SCROLL', 'RING', 'KNIGHT', 'SCROLL', 'SCROLL',
    'KNIGHT', 'RING', 'RING', 'CHEST', 'RING', 'CHEST', 'RING', 'SCROLL',
    'ARCHER', 'MAGE', 'COIN', 'CHEST', 'RING', 'COIN', 'COIN', 'DRAGON',
    'RING', 'SCROLL', 'COIN', 'KNIGHT', 'RING', 'GEM', 'COIN', 'RING',
    'MAGE', 'COIN', 'CROWN', 'CHEST', 'GEM', 'CROWN', 'SCROLL', 'SCROLL',
    'COIN', 'SCROLL', 'CHEST', 'COIN', 'SCROLL', 'CROWN', 'CROWN', 'RING',
    'SCROLL', 'SCROLL', 'CHEST', 'GEM', 'RING', 'SCROLL', 'DRAGON', 'ARCHER',
    'CHEST', 'CHEST', 'RING', 'SCROLL', 'CROWN', 'KNIGHT', 'SCROLL', 'COIN',
    'KNIGHT', 'CHEST', 'MAGE', 'COIN', 'COIN', 'CHEST', 'RING', 'ARCHER',
    'CROWN', 'CHEST', 'CHEST', 'CROWN', 'SCROLL', 'RING', 'CROWN', 'COIN',
    'CHEST', 'COIN', 'RING', 'COIN', 'GEM', 'SCROLL', 'SCROLL', 'CROWN',
    'COIN', 'GEM', 'COIN', 'GEM', 'SCROLL', 'CHEST', 'GEM', 'COIN',
    'SCROLL', 'COIN', 'SCROLL', 'CROWN', 'ARCHER', 'SCROLL', 'CROWN', 'COIN',
    'SCROLL', 'CHEST', 'RING', 'KNIGHT', 'ARCHER', 'SCROLL', 'COIN', 'COIN',
    'RING', 'SCROLL', 'COIN', 'RING', 'SCROLL', 'MAGE', 'SCROLL', 'SCROLL',
    'MAGE', 'SCROLL', 'RING', 'MAGE', 'RING', 'RING', 'CHEST', 'COIN',
    'ARCHER', 'DRAGON', 'COIN', 'ARCHER', 'DRAGON', 'COIN', 'SCROLL', 'SCROLL',
    'GEM', 'GEM', 'RING', 'COIN', 'ARCHER', 'SCROLL', 'COIN', 'CROWN',
    'COIN', 'SCROLL', 'CROWN', 'RING', 'KNIGHT', 'COIN', 'SCROLL', 'CHEST',
  ],
  // Reel 4 — 200 stops
  [
    'RING', 'SCROLL', 'ARCHER', 'RING', 'RING', 'ARCHER', 'RING', 'GEM',
    'SCROLL', 'SCROLL', 'CHEST', 'RING', 'COIN', 'SCROLL', 'SCROLL', 'RING',
    'MAGE', 'RING', 'SCROLL', 'MAGE', 'SCROLL', 'COIN', 'MAGE', 'COIN',
    'RING', 'GEM', 'CHEST', 'SCROLL', 'GEM', 'KNIGHT', 'COIN', 'SCROLL',
    'COIN', 'CHEST', 'SCROLL', 'COIN', 'DRAGON', 'RING', 'COIN', 'SCROLL',
    'SCROLL', 'COIN', 'COIN', 'SCROLL', 'SCROLL', 'COIN', 'SCROLL', 'COIN',
    'CHEST', 'COIN', 'SCROLL', 'COIN', 'COIN', 'RING', 'CHEST', 'COIN',
    'RING', 'CROWN', 'COIN', 'COIN', 'SCROLL', 'COIN', 'SCROLL', 'DRAGON',
    'COIN', 'MAGE', 'CHEST', 'GEM', 'KNIGHT', 'SCROLL', 'RING', 'SCROLL',
    'COIN', 'RING', 'SCROLL', 'RING', 'RING', 'COIN', 'ARCHER', 'SCROLL',
    'SCROLL', 'CHEST', 'MAGE', 'SCROLL', 'RING', 'DRAGON', 'SCROLL', 'SCROLL',
    'RING', 'CROWN', 'COIN', 'RING', 'COIN', 'ARCHER', 'RING', 'CHEST',
    'RING', 'SCROLL', 'MAGE', 'CROWN', 'GEM', 'SCROLL', 'COIN', 'KNIGHT',
    'SCROLL', 'RING', 'CHEST', 'RING', 'SCROLL', 'MAGE', 'CHEST', 'COIN',
    'CROWN', 'COIN', 'GEM', 'KNIGHT', 'COIN', 'RING', 'SCROLL', 'GEM',
    'COIN', 'CROWN', 'RING', 'CHEST', 'KNIGHT', 'COIN', 'SCROLL', 'KNIGHT',
    'SCROLL', 'SCROLL', 'GEM', 'COIN', 'CROWN', 'CROWN', 'COIN', 'COIN',
    'ARCHER', 'CROWN', 'SCROLL', 'RING', 'GEM', 'ARCHER', 'SCROLL', 'CROWN',
    'ARCHER', 'GEM', 'CHEST', 'CROWN', 'SCROLL', 'SCROLL', 'KNIGHT', 'RING',
    'GEM', 'COIN', 'COIN', 'CHEST', 'SCROLL', 'ARCHER', 'RING', 'CHEST',
    'RING', 'GEM', 'GEM', 'COIN', 'CHEST', 'SCROLL', 'COIN', 'DRAGON',
    'SCROLL', 'ARCHER', 'DRAGON', 'SCROLL', 'RING', 'ARCHER', 'CHEST', 'SCROLL',
    'CROWN', 'SCROLL', 'CHEST', 'SCROLL', 'SCROLL', 'RING', 'GEM', 'COIN',
    'CHEST', 'CROWN', 'COIN', 'CHEST', 'RING', 'KNIGHT', 'COIN', 'RING',
    'KNIGHT', 'RING', 'CHEST', 'ARCHER', 'CHEST', 'SCROLL', 'CHEST', 'CROWN',
  ],
  // Reel 5 — 200 stops
  [
    'SCROLL', 'CHEST', 'CHEST', 'KNIGHT', 'RING', 'COIN', 'COIN', 'ARCHER',
    'CHEST', 'SCROLL', 'CROWN', 'MAGE', 'ARCHER', 'SCROLL', 'COIN', 'SCROLL',
    'SCROLL', 'RING', 'RING', 'ARCHER', 'KNIGHT', 'SCROLL', 'CROWN', 'RING',
    'SCROLL', 'COIN', 'SCROLL', 'COIN', 'COIN', 'KNIGHT', 'COIN', 'DRAGON',
    'RING', 'CHEST', 'SCROLL', 'COIN', 'RING', 'COIN', 'DRAGON', 'SCROLL',
    'CHEST', 'SCROLL', 'CHEST', 'SCROLL', 'COIN', 'SCROLL', 'RING', 'GEM',
    'RING', 'RING', 'SCROLL', 'ARCHER', 'SCROLL', 'RING', 'ARCHER', 'MAGE',
    'DRAGON', 'COIN', 'GEM', 'GEM', 'CROWN', 'CROWN', 'RING', 'COIN',
    'CROWN', 'RING', 'CHEST', 'RING', 'SCROLL', 'COIN', 'CROWN', 'MAGE',
    'SCROLL', 'COIN', 'CHEST', 'SCROLL', 'COIN', 'RING', 'RING', 'ARCHER',
    'SCROLL', 'CHEST', 'CROWN', 'CHEST', 'RING', 'GEM', 'RING', 'SCROLL',
    'GEM', 'CROWN', 'CROWN', 'CHEST', 'SCROLL', 'ARCHER', 'SCROLL', 'COIN',
    'RING', 'RING', 'CHEST', 'SCROLL', 'RING', 'CHEST', 'CHEST', 'KNIGHT',
    'RING', 'RING', 'KNIGHT', 'SCROLL', 'COIN', 'COIN', 'SCROLL', 'SCROLL',
    'GEM', 'RING', 'COIN', 'SCROLL', 'COIN', 'GEM', 'RING', 'SCROLL',
    'ARCHER', 'GEM', 'RING', 'ARCHER', 'COIN', 'CROWN', 'SCROLL', 'COIN',
    'GEM', 'SCROLL', 'COIN', 'RING', 'COIN', 'SCROLL', 'GEM', 'RING',
    'SCROLL', 'CHEST', 'RING', 'CHEST', 'CROWN', 'SCROLL', 'CHEST', 'GEM',
    'COIN', 'SCROLL', 'KNIGHT', 'RING', 'COIN', 'GEM', 'COIN', 'RING',
    'GEM', 'SCROLL', 'GEM', 'CROWN', 'ARCHER', 'COIN', 'KNIGHT', 'COIN',
    'DRAGON', 'KNIGHT', 'COIN', 'DRAGON', 'CROWN', 'COIN', 'SCROLL', 'CHEST',
    'MAGE', 'ARCHER', 'SCROLL', 'COIN', 'SCROLL', 'COIN', 'CHEST', 'SCROLL',
    'CHEST', 'RING', 'SCROLL', 'SCROLL', 'CHEST', 'SCROLL', 'RING', 'CHEST',
    'COIN', 'COIN', 'SCROLL', 'SCROLL', 'COIN', 'COIN', 'SCROLL', 'SCROLL',
    'MAGE', 'KNIGHT', 'RING', 'MAGE', 'COIN', 'COIN', 'MAGE', 'SCROLL',
  ],
] as const
